version: '3.8'

services:
  # Nama layanan Anda, misalnya 'webserver'
  nginx-server:
    # Perintah untuk membangun image dari Dockerfile di direktori ini.
    build: .
    # Beri nama dan versi pada image yang akan dibuat.
    image: my-static-website:1.0
    # Petakan port 80 (HTTP standar) di server Anda ke port 80 di dalam kontainer.
    ports:
      - "80:80"
    # Atur agar kontainer selalu restart secara otomatis.
    restart: always
```html
<!-- FILE 2: index.html -->
<!-- Ini adalah konten website Anda. Anda bisa menambahkan file CSS dan JS juga. -->

<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Website dari Nginx</title>
    <style>
        body { font-family: sans-serif; display: flex; justify-content: center; align-items: center; height: 100vh; background-color: #f0f2f5; margin: 0; }
        .container { text-align: center; padding: 40px; background-color: white; border-radius: 10px; box-shadow: 0 4px 8px rgba(0,0,0,0.1); }
        h1 { color: #333; }
        p { color: #666; }
    </style>
</head>
<body>
    <div class="container">
        <h1>Halo, Dunia!</h1>
        <p>Website ini berhasil disajikan oleh Nginx di dalam sebuah kontainer Docker.</p>
    </div>
</body>
</html>
```dockerfile