
version: '3.8'

services:
  # Nama layanan Anda, misalnya 'webserver'
  nginx-server:
    # Perintah untuk membangun image dari Dockerfile di direktori ini.
    build: .
    # Beri nama dan versi pada image yang akan dibuat.
    image: my-static-website:1.0
    # Petakan port 80 (HTTP standar) di server Anda ke port 80 di dalam kontainer.
    ports:
      - "80:80"
    # Atur agar kontainer selalu restart secara otomatis.
    restart: always
